GEMINI_API_KEY="AIzaSyAhindixQniyA77PlbN-Ote-T5JbHA-Jhg"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxamRnYXBmbXhzY3ZqdGdwa2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0MDc5MDMsImV4cCI6MjA0NTk4MzkwM30.XtU9hXu-0N4luLCsoZJlOlv7VFE7CAauZDv9yG0Gja4"
SUPABASE_URL="https://wqjdgapfmxscvjtgpkcx.supabase.co"


